name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: git clone https://github.com/ronin8881/ronin8881.github.io.git
    - run: cp dist/* ronin8881.github.io/
    - run: cd ronin8881.github.io/
    - run: git commit -m "deploy commit"
    - run: git push -u origin master
      env:
        CI: true
